export const FETCH_NEWS = "FETCH_NEWS";
export const BOOKMARK_NEWS = "BOOKMARK_NEWS";
export const REMOVE_NEWS = "REMOVE_NEWS";
export const SEARCH_NEWS = "SEARCH_NEWS";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const TOGGLE_BOOKMARK = "TOGGLE_BOOKMARK";
export const INITIALIZE_BOOKMARKS = "INITIALIZE_BOOKMARKS";
